---
branches:
  only:
    - master

env:
  global:
    # DOCKER_EMAIL
    - secure: "BBHJoYTL9yqhANHiwkuMIfUampo8MvTbHTgQ14xPFezG/AZW5GG4tAR7tCcICESOYyqll1tTqi7l3ce3tlAWNUg6eD8zb4e2Dm7hCMrQsOnH5rcOGgiEtA43954HoYS2BNzsl8N14A1Ll5X1VjsP2rJsWJ7VRHrWaWxJyTfKQYxHwQa4MuApq69osoa1balSxpltPn+/6AQ1tj85duKSKwox+aZ/zaNd9U8zvBaEuHy4Av4W2cSIs7n5wfL3Lcr4SdSkSE1ZmyNlkU5VjupEHiSbvRaCxn3DOfOt92VFs4tXvr8K2IirN2RYl6/4vBihvsR/C6aJaMyNYna3Cyg8Zk/LFJjS1qyKgXcWWjvV7wQY7ukVLhnzow984gs5Gqmvz5WTWsIHs6fYj9tSENo/YzQZWg07WSBf7Cbm5WNKhCdVVjABjX1AS0yaAPmf0rxXirJfGCM/JeYs7ZbGwJlKqfFLwxKA6MQ2pU/FteY5rF6V2D4z6ls2CZ/E2+QcSn1VJtKWIvlhxN6LMgNe0BjFSzpWfo1q0TlAxDVjcZUB1CaGJT2FPfcA1cx6jHZ1hk4+p+GsURV/sbrv34ghBc9qTWPjqw3ypl1K1URKcE/Y/82eEAQm09RcRmO8HKwm3pV400FP367bfoCJILsNBhCs4gWc8pkdRTu9JYn2dMQOBUs="
    # DOCKER_USER
    - secure: "Ad5y+sNmy37k1qdFXnRltS+pFphBiCa0aLwvwuMx3Ojh0b+o+QzMPc+8RlG4w48z7Yp9Pm2Gng8Ar9ZckEslnZxlpVage7Un4JiJ1r09cVqmBDhl3fHDz//yNdV9s2i3pmFZ3D4rsWeFvW3+URpGtsutYxQhdpV+ArS5r4Y1goXjQgJOAaXEtjEanPp+YMf0PbYIeErqEMBvsc42N5xkwfXOTQc11IdovONTRvVtd9n5rpHFddM2abGQ0sWnJqCHFxSPP/V7rzkBp0Ee3TvJDsrPzJVzlklDY09T7AnD1W9JkKb8eaZPRZU2t3ABCGJwcWw/G3cnjKlszyACHofxJcjSqwLSlCFqDrPWXwdsDTW8SyeOMoMA6VVqbPnv5Zys/EEiaNbTyxPflyr/Z8w9PY95Q47JwVDaK9/ENYgA8jXuq06RPWVELNZlCsVpIgXK3y3N4ptoU2LxVAnp098Iz6hyb7u9IjVMmH6ieU/xGLTBjBW0Dv4vygheFKOw1AIlQuxjph8I95ibrSjImMkZRZzhvpVsBCEf89gaWxIxSAakaVFt22skYuVEd+7D6DFuu57hy+5Sh2zCJf9hTBfwQi8OKzDX/JiUOTn7jLSUv2r4emRYRYPTeb9ILb2SxZKVLC1exgxJd0ZeSgNJnhNV5a3yb5g7H03lnf5HKvau7CU="
    # DOCKER_PASS
    - secure: "FQCz0BM26nuoHUJbqPPTvb+l7GksM/OzyCwSwcxtZqUtDGPxVV73drEfGbn377YHvPmGgb6nxF1IlRwMQldxPfWfD/sJvvnc2ANVOEKzuP+u1ZhcQq6NziIUguXyi2uWe36BBIfpyRDo1aj8nLGcIdCd+9htDRk2WKRvARxWpbebfNFjKGPR3Pi/RwuysmwivG6oEWiImS6PROdAE/9NK/iw1E2S3q97q87zntI5Zl2BcbPsfQ7Mg5MXYAl3k2CuoVHIQI3QBJZdH1A8eO+RXpeOGTbJz1FJWpgRaIhmFlgP9YDImJrdpM2EZLSGLtf0wBfG6J5IlXEV2A4MQ0X1i4PtejBRZ1euTAlLmIFdWvcIdygxlNOZbcTxPHY5Tkg+MN/DlskYfsg9PjLM/KZd8gQkIH4DPAsNsB+HsrrSHRQhkeSA2JtD1XtGYm1dopJbmoA00rKEa3mqTNXZjce5m/n1QvqoqIWZx9Dq745r4T+B0CAc3wZ+UQ6KExtLXoyuk0xXQHyUI2s937Ks/8nDG5bHrSi0THDDRMWdVfSct2YY8gXkt8onOgURxkgpHECwO00L6M9TY9HBwQDz1SlwTdBYwXzmpsd5pbp9rMjCNLF9AO1n4Tj4BLOvdx5yuV731wajd0RpfkyHhKmnUDNlbfqmEnVhLaPfqZxC7kwb1AM="
    - DOCKER_REPO=spreadspace/nginx

script:
  ### pull current images to potentially use docker build cache
  - docker pull $DOCKER_REPO:latest
  ### build the new images
  - docker build -t $DOCKER_REPO:latest .
  - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:latest
